# ---------------------------------------------------------------------------- #
#                              ğŸ”„ Pre-Commit Hooks                             #
# ---------------------------------------------------------------------------- #

repos:
# ---------------------------------------------------- #
#                    ğŸ§ª Unit Tests                     #
# ---------------------------------------------------- #
- repo: local
  hooks:
    - id: unit-tests
      name: "Performing Unit Tests ğŸ§ª  "
      entry: python3 -m unittest discover -s tests
      language: system
      pass_filenames: false

# ---------------------------------------------------- #
#                ğŸ” Code Quality Check                 #
# ---------------------------------------------------- #
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.10
  hooks:
  - id: ruff-format # ---------- Formatting 
    name: "Formatting ğŸ“ "
  - id: ruff-check # ---------- Lint
    name: "Lintting ğŸ“Œ "
    # args:
    # - --fix

# ---------------------------------------------------- #
#                   ğŸ” Security Check                  #
# ---------------------------------------------------- #
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.22.1
  hooks:
  - id: gitleaks
    # args: ["--config", "gitleaks.toml"] # In case of custom rules
    name: "Secrets Leak Scanning ğŸ” "

# ---------------------------------------------------- #
#                    ğŸ“„ Files Check                    #
# ---------------------------------------------------- #
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files 
    name: "Scanning for Large Files ğŸ” "