# ---------------------------------------------------------------------------- #
#                              ğŸ”„ Pre-Commit Hooks                             #
# ---------------------------------------------------------------------------- #

repos:
# ---------------------------------------------------- #
#                    ğŸ§ª Unit Tests                     #
# ---------------------------------------------------- #
- repo: local
  hooks:
    - id: unit-tests
      name: "Performing Unit Tests ğŸ§ª  "
      entry: npm test -- --bail --findRelatedTests
      language: system
      types: [javascript, jsx]

# # ---------------------------------------------------- #
# #                   ğŸ” Security Check                  #
# # ---------------------------------------------------- #

# # ********************************* #
# #  Support: -                       #
# # ********************************* #
# - repo: https://github.com/gitleaks/gitleaks
#   rev: v8.22.1
#   hooks:
#   - id: gitleaks
#     # args: ["--config", "gitleaks.toml"] # In case of custom rules
#     name: "Secrets Leak Scanning ğŸ” "

# # ---------------------------------------------------- #
# #                ğŸ” Code Quality Check                 #
# # ---------------------------------------------------- #

# # ********************************* #
# #  Support: JS[X], TS[X], JSON, CSS #
# # ********************************* #
# - repo: https://github.com/biomejs/pre-commit
#   rev: v2.1.2
#   hooks:
#   - id: biome-format # ---------- Formatting 
#     name: "Formatting ğŸ“ "
#   - id: biome-lint # ---------- Lint
#     name: "Lintting ğŸ“Œ "
#   - id: biome-check # ---------- Final Check
#     name: "Final Check ğŸ—ƒï¸  "

# # ---------------------------------------------------- #
# #                    ğŸ“„ Files Check                    #
# # ---------------------------------------------------- #

# - repo: https://github.com/pre-commit/pre-commit-hooks
#   rev: v5.0.0
#   hooks:
#   - id: check-added-large-files 
#     name: "Scanning for Large Files ğŸ” "